name: ds-101
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_1003
  - astroid=2.2.5=py37_0
  - astropy=3.2.1=py37h516909a_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - confuse=1.0.0=py_0
  - cryptography=2.7=py37h72c5cf5_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py37_1000
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - htmlmin=0.1.12=py_1
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_1000
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.21=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.2=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - lazy-object-proxy=1.4.2=py37h516909a_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - llvmlite=0.29.0=py37hfd453ef_1
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.1.1=py37h5429711_0
  - mccabe=0.6.1=py_1
  - missingno=0.4.2=py_0
  - mistune=0.8.4=py37h14c3975_1000
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - more-itertools=7.2.0=py_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=he6710b0_1
  - numba=0.45.1=py37hb3f55d8_0
  - numpy=1.16.5=py37h7e9f1db_0
  - numpy-base=1.16.5=py37hde5b4d6_0
  - openssl=1.1.1c=h516909a_0
  - packaging=19.0=py_0
  - pandas=0.25.1=py37he6710b0_0
  - pandas-profiling=2.3.0=py_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - phik=0.9.8=py_0
  - pickleshare=0.7.5=py37_0
  - pip=19.2.2=py37_0
  - pluggy=0.13.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - psutil=5.6.3=py37h516909a_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.0=py_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pylint=2.3.1=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.4=py37h516909a_0
  - pysocks=1.7.0=py37_0
  - pytest=5.1.2=py37_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.5.0=py_0
  - pytest-doctestplus=0.3.0=py_1
  - pytest-openfiles=0.4.0=py_0
  - pytest-pylint=0.14.1=py_0
  - pytest-remotedata=0.3.1=py_0
  - pytest-runner=5.1=py_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h516909a_0
  - pyzmq=18.1.0=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - scipy=1.3.1=py37h7c811a0_0
  - seaborn=0.9.0=py_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.10.1=py37hc1659b7_0
  - testpath=0.4.2=py_1001
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.25.3=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py_1
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - swmat==0.1.4
prefix: /home/efim/anaconda3/envs/ds-101

